"use client";
import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from"react";
import{Product,products}from"../data/products";
export type CartItem={product:Product;quantity:number};
export type Order={id:string;createdAt:string;items:CartItem[];subtotal:number;shipping:number;discount:number;fee:number;total:number;payment:string;deliveryDate:string;deliveryTime:string;note:string;status:string};
type Store={items:CartItem[];favorites:string[];orders:Order[];toast:string;add:(p:Product,n?:number)=>void;remove:(id:string)=>void;change:(id:string,n:number)=>void;clear:()=>void;toggleFavorite:(id:string)=>void;placeOrder:(details:Omit<Order,"id"|"createdAt"|"items"|"subtotal"|"status">)=>Order|null;subtotal:number;count:number};
const C=createContext<Store|null>(null);
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}}
export function StoreProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<CartItem[]>(()=>read("tt-cart",[]));const[favorites,setFavorites]=useState<string[]>(()=>read("tt-favs",[]));const[orders,setOrders]=useState<Order[]>(()=>read("tt-orders",[]));const[toast,setToast]=useState("");const notify=useCallback((message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)},[]);useEffect(()=>localStorage.setItem("tt-cart",JSON.stringify(items)),[items]);useEffect(()=>localStorage.setItem("tt-favs",JSON.stringify(favorites)),[favorites]);useEffect(()=>localStorage.setItem("tt-orders",JSON.stringify(orders)),[orders]);const subtotal=items.reduce((sum,item)=>sum+item.product.price*item.quantity,0);const add=useCallback((product:Product,quantity=1)=>{setItems(current=>{const found=current.find(i=>i.product.id===product.id);return found?current.map(i=>i.product.id===product.id?{...i,quantity:i.quantity+quantity}:i):[...current,{product,quantity}]});notify(`${product.name}をカートに追加しました`)},[notify]);const placeOrder=useCallback((details:Omit<Order,"id"|"createdAt"|"items"|"subtotal"|"status">)=>{if(!items.length)return null;const now=new Date();const order:Order={...details,id:`TT${now.getFullYear()}${String(now.getMonth()+1).padStart(2,"0")}${String(now.getDate()).padStart(2,"0")}-${String(Date.now()).slice(-6)}`,createdAt:now.toISOString(),items:items.map(i=>({...i})),subtotal,status:"注文受付"};setOrders(current=>[order,...current]);setItems([]);notify("ご注文を受け付けました");return order},[items,subtotal,notify]);const value=useMemo<Store>(()=>({items,favorites,orders,toast,add,remove:(id)=>{setItems(x=>x.filter(i=>i.product.id!==id));notify("商品を削除しました")},change:(id,n)=>setItems(x=>n<1?x.filter(i=>i.product.id!==id):x.map(i=>i.product.id===id?{...i,quantity:n}:i)),clear:()=>{setItems([]);notify("カートを空にしました")},toggleFavorite:(id)=>{setFavorites(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);notify("お気に入りを更新しました")},placeOrder,subtotal,count:items.reduce((sum,item)=>sum+item.quantity,0)}),[items,favorites,orders,toast,add,placeOrder,subtotal,notify]);return <C.Provider value={value}>{children}{toast&&<div className="toast" role="status">✓ {toast}</div>}</C.Provider>}
export function useStore(){const value=useContext(C);if(!value)throw new Error("StoreProvider is missing");return value}export const favProducts=(ids:string[])=>products.filter(p=>ids.includes(p.id));
